define({
    root: ({
        _widgetLabel: "Workflow Manager Create Job",
        title: "Create a Workflow Manager Job",
        selectFeatures: "Select Features",
        drawLocation: "Draw Location",
        photoGeotag: "Photo Geotag",
        selectDrawMode: "Select AOI draw mode",
        usernameLabel: "Username",
        nameLabel: "Name",
        emailLabel: "Email",
        phoneLabel: "Phone",
        useArcGISOnlineUsersLabel: "ArcGIS Online",
        useWMXUsersLabel: "Workflow Manager Users",
        jobNameLabel: "Job Type",
        addGeotagLabel: "Add Geotag Photos",
        choosePhotoButtonLabel: "Choose Photo",
        notesLabel: "Comments",
        noAttachments: "No Attachments",
        noFilename: "No Filename",
        attachmentTitle: "Filename",
        attachmentType: "Type",
        browserBtnCaption: "Choose a File",
        wmxJobTypeName: "Data Edits",
        createJobBtnLabel: "Create Job",
        submitJobBtnLabel: "Submit Job",
        cancelBtnLabel: "Cancel",
        addLocationLabel: "Location Tab",
        selectFeaturesLabel: "Select Features"
    }),
});